### PR TITLE
Incorporate S/MIME BR OIDs

### PR DESCRIPTION
**Pull request by XolphinMartijn**
This PR replaces #239

### CODE REVIEW

**Comment by Court72** [comment]
@kasirota

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by BuckeyeGuyJFlo** [comment]
#label:"awaiting-product-team-response"

**Review by hasokol-ms — APPROVED** [review]
Thank you Martijn for putting this together!

**Comment by hasokol-ms** [comment]
#sign-off

**Pull request merged**
