### PR TITLE
Update incident-response-playbook-app-consent.md

### PR DESCRIPTION
**Pull request by msbemba**
updated the Script link in the document.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5793

**Comment by msbemba** [comment]
@Yogkumit This is a Different Repo but I have access to create a PR. Joe Davis is the Author.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please merge this PR. Thanks.

**Comment by JoeDavies-MSFT** [comment]
I published this change via a different PR. See https://docs.microsoft.com/en-us/security/compass/incident-response-playbook-app-consent to confirm.

**Comment by msbemba** [comment]
Thank you @JoeDavies-MSFT

**Pull request closed without merging**
