### PR TITLE
Create december-2024

### PR DESCRIPTION
**Pull request by kasirota**
Add december release

### CODE REVIEW

**Comment by ttorble** [comment]
Hi @kasirota - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. Would you make this content update in the private repo instead? Thank you! We'll close this PR.

**Comment by kasirota** [comment]
@ttorble, which is the private repo?

**Comment by ttorble** [comment]
@kasirota the private repo is here: https://github.com/MicrosoftDocs/security-pr (`security-pr` rather than `security`). https://github.com/MicrosoftDocs/security is the repo for public contributions. New articles can't be merged to the public repo.

It looks like you usually work in the private repo: https://github.com/MicrosoftDocs/security-pr/pulls?q=is%3Apr+author%3Akasirota

**Comment by kasirota** [comment]
@tahmad2, I'm not going to be able to fit this fix through my private repo before I leave. Can you check this out on Monday?

**Pull request closed without merging**
